tinyMCE.addI18n('en.table_dlg',{
general_tab:"General",
advanced_tab:"Avancé",
general_props:"Propriétés général",
advanced_props:"Propriétés avancés",
rowtype:"Row in table part",
title:"Insérer/modifier table",
width:"Largeur",
height:"Hauteur",
cols:"Colonnes",
rows:"Lignes",
cellspacing:"Espace entre les cellules",
cellpadding:"Cellpadding",
border:"Bordure",
align:"Alignement",
align_default:"Default",
align_left:"Gauche",
align_right:"Droite",
align_middle:"Centrer",
row_title:"Propriétés des lignes",
cell_title:"Propriétés des cellules",
cell_type:"Type de cellule",
valign:"Alignement vertical",
align_top:"Haut",
align_bottom:"Bas",
bordercolor:"Couleur de bordure",
bgcolor:"Couleur de fond",
merge_cells_title:"Fusionner les cellules de la table",
id:"Id",
style:"Style",
langdir:"Direction de l'ecriture",
langcode:"Language code",
mime:"Type MIME cible",
ltr:"Gauche a droite",
rtl:"Droite a gauche",
bgimage:"Image de fond",
summary:"Sommaire",
td:"Donnée",
th:"Header",
cell_cell:"Update current cell",
cell_row:"Update all cells in row",
cell_col:"Update all cells in column",
cell_all:"Update all cells in table",
row_row:"Update current row",
row_odd:"Update odd rows in table",
row_even:"Update even rows in table",
row_all:"Update all rows in table",
thead:"Table Head",
tbody:"Table Body",
tfoot:"Table Foot",
scope:"Scope",
rowgroup:"Row Group",
colgroup:"Col Group",
col_limit:"You've exceeded the maximum number of columns of {$cols}.",
row_limit:"You've exceeded the maximum number of rows of {$rows}.",
cell_limit:"You've exceeded the maximum number of cells of {$cells}.",
missing_scope:"Are you sure you want to continue without specifying a scope for this table header cell. Without it, it may be difficult for some users with disabilities to understand the content or data displayed of the table.",
caption:"Table caption",
frame:"Frame",
frame_none:"none",
frame_groups:"groups",
frame_rows:"rows",
frame_cols:"cols",
frame_all:"all",
rules:"Rules",
rules_void:"void",
rules_above:"above",
rules_below:"below",
rules_hsides:"hsides",
rules_lhs:"lhs",
rules_rhs:"rhs",
rules_vsides:"vsides",
rules_box:"box",
rules_border:"border"
});