tinyMCE.addI18n('en.advlink_dlg',{
title:"Insérer/Editer un lien",
url:"URL du lien",
target:"Cible",
titlefield:"Tire",
is_email:"The URL you entered seems to be an email address. Do you want to add the required mailto: prefix?",
is_external:"The URL you entered seems to be an external link. Do you want to add the required http:// prefix?",
list:"Liste de lien",
general_tab:"General",
popup_tab:"Popup",
events_tab:"Evenements",
advanced_tab:"Avancé",
general_props:"Propriétés générales",
popup_props:"Propriétés popup",
event_props:"Evenenements",
advanced_props:"Propriétés avancés",
popup_opts:"Options",
anchor_names:"Ancres",
target_same:"Ouvrir dans cette fenetre",
target_parent:"Ouvrir dans la fenetre parente",
target_top:"Ouvrir dans le cadre du haut (remplace tout les cadre)",
target_blank:"Ouvrir dans une nouvelle fenetre",
popup:"Javascript popup",
popup_url:"Popup URL",
popup_name:"Nom de la fenetre",
popup_return:"Insert 'return false'",
popup_scrollbars:"Afficher la barre de défilement",
popup_statusbar:"Afficher la barre de statut",
popup_toolbar:"Afficher la barre d'outils",
popup_menubar:"Afficher la barre de menu",
popup_location:"Afficher la barre d'adresse",
popup_resizable:"Fenetre redimensionnable",
popup_dependent:"Dependent (Mozilla/Firefox only)",
popup_size:"Taille",
width:"Largeur",
height:"Hauteur",
popup_position:"Position (X/Y)",
id:"Id",
style:"Style",
classes:"Classes",
target_name:"Nom de la cible",
langdir:"Language direction",
target_langcode:"Langue cible",
langcode:"Language code",
encoding:"Target character encoding",
mime:"Target MIME type",
rel:"Relationship page to target",
rev:"Relationship target to page",
tabindex:"Tabindex",
accesskey:"Accesskey",
ltr:"Left to right",
rtl:"Right to left",
link_list:"Link list"
});